### ISSUE TITLE
Can not parse Soundcloud, youtube, Facebook, Vine.

### ISSUE THREAD

**Issue by xtreme8210** [aboutsajjad/Bridge#1]
Hi Aboutsajjad,

Thank you for making this "Bridge" project, I find it very useful.
But I have tested some sites and it is not working proper.

I have tried to cache these down below 
Soundcloud : https://soundcloud.com/nardeen-ibrahim/adele-when-we-were-young
****I got album's jpg file instead if mp3 file.
Youtube: https://www.youtube.com/watch?v=DDWKuo3gXMQ
****I got html ands wf files.
Facebook: https://www.facebook.com/100000024006299/videos/1614327285244723/
****I got pop up message "Nothing found!"
Vine: https://vine.co/v/5nPPVinznwl
****I got an vine home page png file

please let me know if I did not test it right.

**Comment by aboutsajjad** [comment]
Hi Sorry i know it's not complete version here, i could't push it because of my internet connection, 
just wait few hours i am gonna push complete version from local repository .

**Comment by xtreme8210** [comment]
Thank you very much. :-)
