### ISSUE TITLE
Server inside build,  I got this error "No such modules 'FileExplorer'"

### ISSUE THREAD

**Issue by xtreme8210** [aboutsajjad/Bridge#3]
Hi Aboutsajjad,

I tried to compile the server side build and I got this error :
No such modules 'FileExplorer'

I can not find 'FileExplorer' in the project.

**Comment by xtreme8210** [comment]
Update for my problem, I found out Podfile didn't have pod "FileExplorer", "~> 1.0.4" so I add it and do the pod install. So now FileExplorer not found problem solved. 

But another problem comes up, as below:

ld: warning: ignoring file /Users/mac/Downloads/Bridge-withServerInside/Python.framework/Python, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): /Users/mac/Downloads/Bridge-withServerInside/Python.framework/Python
Undefined symbols for architecture arm64:
  "_Py_DecodeLocale", referenced from:
      ___25-[YouTube_dl run_server:]_block_invoke in NSObject+youtube_dl.o
  "_Py_SetPythonHome", referenced from:
      ___25-[YouTube_dl run_server:]_block_invoke in NSObject+youtube_dl.o
  "_Py_Finalize", referenced from:
      ___25-[YouTube_dl run_server:]_block_invoke in NSObject+youtube_dl.o
  "_PySys_SetArgv", referenced from:
      ___25-[YouTube_dl run_server:]_block_invoke in NSObject+youtube_dl.o
  "_Py_Initialize", referenced from:
      ___25-[YouTube_dl run_server:]_block_invoke in NSObject+youtube_dl.o
  "_PyMem_RawMalloc", referenced from:
      ___25-[YouTube_dl run_server:]_block_invoke in NSObject+youtube_dl.o
  "_PyEval_InitThreads", referenced from:
      ___25-[YouTube_dl run_server:]_block_invoke in NSObject+youtube_dl.o
  "_PyRun_SimpleFileExFlags", referenced from:
      ___25-[YouTube_dl run_server:]_block_invoke in NSObject+youtube_dl.o
  "_PyMem_RawFree", referenced from:
      ___25-[YouTube_dl run_server:]_block_invoke in NSObject+youtube_dl.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by aboutsajjad** [comment]
Oh i see python executable is over 100MB and i used git-lfs to upload that but it turns out it didn't work
please download [Python-3.5-iOS-support](https://github.com/pybee/Python-Apple-support/releases/download/3.5-b3/Python-3.5-iOS-support.b3.tar.gz) and replace files in project directory and pull latest commits.

**Comment by xtreme8210** [comment]
Thank you very much, it is working perfectly.
