### ISSUE TITLE
NSURLErrorDomain Code=-1004 "Could not connect to the server

### ISSUE THREAD

**Issue by xtreme8210** [aboutsajjad/Bridge#6]
Hi I have create my own project and transfer to objective c but I have getting this error below, am I missing something?  
Tried these and still not working, Please help
solution 1. 
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
</dict>

solution 2.
Checked my HTTP/1.1
HTTP/1.1 302 Moved Temporarily
Server: nginx/1.11.13
Date: Thu, 17 Aug 2017 09:46:25 GMT
Content-Type: text/html
Content-Length: 162
Connection: keep-alive
Keep-Alive: timeout=20
Location: https://www.test.com/
X-DIS-Request-ID: 5a24371f22fb184812dd5a1c7a9615c5

Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={NSUnderlyingError=0x608000646390 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, NSErrorFailingURLStringKey=http://127.0.0.1:9191/api/info?flatten=False&url=https%3A//m.youtube.com/watch?v%3DKWGrPNqz4uc, NSErrorFailingURLKey=http://127.0.0.1:9191/api/info?flatten=False&url=https%3A//m.youtube.com/watch?v%3DKWGrPNqz4uc, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=61, NSLocalizedDescription=Could not connect to the server.

I code below
//创建管理者对象
static NSString *baseUrl = @"http://127.0.0.1:9191";

    AFHTTPSessionManager *mgr = [AFHTTPSessionManager manager];
    
    //配置参数
    NSString *str = [NSString stringWithFormat:@"%@/api/info", baseUrl];
    NSMutableDictionary *params = [NSMutableDictionary dictionary];
    params[@"url"] = urlString;
    params[@"flatten"] = @"False";
    
    //发送请求
    [mgr GET:str parameters:params progress:^(NSProgress * _Nonnull downloadProgress) {
        NSLog(@"%@",downloadProgress);
    } success:^(NSURLSessionDataTask * _Nonnull task, id  _Nullable responseObject) {
        NSLog(@"%@",responseObject);
        
        NSInteger statusCode = 0;
        
        if ([task.response isKindOfClass:[NSHTTPURLResponse class]]) {
            NSHTTPURLResponse *httpResponse = (NSHTTPURLResponse *)task.response;
            statusCode = httpResponse.statusCode;
        }
        
        switch (statusCode) {
            case 200:
                completion(responseObject, true);
                break;
            case 400:
                [GV showMsg:@"Error" andContent:@"400 Bad Request – invalid query parameters" andCancelTitle:@"OK"];
                completion(nil, false);
                break;
            case 500:
                [GV showMsg:@"Error" andContent:@"500 Internal Server Error – the extraction fails, Please check your URL" andCancelTitle:@"OK"];
                completion(nil, false);
                break;
            default:
                NSLog(@"Default");
                completion(nil, false);
                break;
        }
    } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
        NSLog(@"request failed");
        [GV showMsg:@"Error" andContent:error.localizedDescription andCancelTitle:@"OK"];
        completion(nil, false);
    }];

**Comment by aboutsajjad** [comment]
There is a flask web-server inside app you should call the function to initialize the server [Line 30](https://github.com/aboutsajjad/Bridge/blob/ee76ae023843038a3dd5874dfa838760e79d10bc/Bridge/NSObject%2BObjcFlask.m#L30)
or just use latest version on master which calls direct python function without flask.

**Comment by xtreme8210** [comment]
Hi Aboutsajjad, thank you for your reply, I have tried to run_server, when I compile it on the simulator, it just crash straight away. I am sure what is going on here. 
Please help me, thank you

### My code below:
`
@property (nonatomic, strong) ObjcFlask *youtube_dl;

-(void)initobject {
    self.youtube_dl = [ObjcFlask new];
}`

### Your code below:
`func initobject() {
        self.youtube_dl = ObjcFlask() 
    }`

1. Called in didFinishLaunchingWithOptions
![2017-08-18 3 04 10](https://user-images.githubusercontent.com/2245528/29447889-99aee3cc-8426-11e7-9ff8-162f54ae2c4d.png)
2. This is the same as API.swift's function in your bridge.project
![2017-08-18 3 04 01](https://user-images.githubusercontent.com/2245528/29447911-b03a5ba8-8426-11e7-9235-5520f6dff965.png)
3. Copied from your project
![2017-08-18 3 03 53](https://user-images.githubusercontent.com/2245528/29447917-b63b4fd0-8426-11e7-9a51-df77150dadb1.png)
4. Error here
![2017-08-18 3 03 32](https://user-images.githubusercontent.com/2245528/29447927-c0d7160e-8426-11e7-8cdf-a2b0060eed1e.png)

**Comment by aboutsajjad** [comment]
I don't know much about Objective-c but don't put `py_Initialize();` inside Object default init function, create new function and call the new function maybe that would work.
If it doesn't just let me know i will try and test it with Objective-c.

**Comment by xtreme8210** [comment]
Thank you for the reply, I have installed the python3 and run the simulator, I now get this error:

Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: unable to load the file system codec
ImportError: No module named 'encodings'

Current thread 0x0000000113e0f3c0 (most recent call first):

I am still googling this error and trying to find out how to fix it. 
Please help me if you ran into this error before and thank you.
