### ISSUE TITLE
This bundle is invalid - The Info.plist file for /Payload/iConnect PLFS.app/Library/Python.framework is missing or could not be read.

### ISSUE THREAD

**Issue by xtreme8210** [aboutsajjad/Bridge#8]
Hi, I am trying to update my app on the App Store, but I got this issue, Please help me.

I got the same problem as this link below after I upload to iTunes connect: https://github.com/daltoniam/SwiftHTTP/issues/207

I got email from Apple team as below:

Dear developer,

We have discovered one or more issues with your recent delivery for "PQI iConnect". To process your delivery, the following issues must be corrected:

This bundle is invalid - The Info.plist file for /Payload/iConnect PLFS.app/Library/Python.framework is missing or could not be read.

Invalid Bundle - The bundle at '/Payload/iConnect PLFS.app/Library/Python.framework' does not contain a bundle executable.

Once these issues have been corrected, you can then redeliver the corrected binary.

Regards,

The App Store team

**Comment by aboutsajjad** [comment]
Sorry but i don't have any experience with AppStore and iTunes Connect Because of Apple limit on my country.
